### PR TITLE
Issue#7 documentation fixes

### PR DESCRIPTION
**Pull request by fpuga**
A couple of improvements to the Bucardo documentation.

I try to keep the commits small with descriptions that explain the changes because some of them are a bit "opinative"

Please feel free to make suggestions, drop the commits you don't want or whatever. Feel free to squash the changes, or ask to any other improvements. Just let me know if you prefer additional commits or `push --force` over this branch.

I think that there is a lot more that can be done, but keep the doc up to date with the code seems a bit difficult, and "expertise" in the code is needed. Also I'm not sure if would invest more time on this.

Kudos for Bucardo devs.

refs #7

### CODE REVIEW

**Comment by machack666** [comment]
Thanks for the improvements; a lot of good things in here.  Will probably take as-is; the main thing is we'll want to make sure any old files get 301'd to the new document for the items that have been removed.

**Comment by fpuga** [comment]
Fair enough for me. Just don't hesitate and ask for whatever change you think is need.

**Comment by jonjensen** [comment]
@fpuga Sorry this languished for a while. Thank you very much!

**Comment by fpuga** [comment]
Thanks @jonjensen. Nice to see it integrated. I know how hard it is keep and free software project up to date, so no worries.

**Pull request merged**
